version: '3'

networks:
  sqlserver-network:
    driver: bridge
  
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sql-server
    container_name: sql-server
    restart: unless-stopped
    ports:
      - "1433:1433"
    volumes:
      - ${PWD}/fs/volumes/sqlserver/data:/var/opt/mssql/data
      - ${PWD}/fs/volumes/sqlserver/log:/var/opt/mssql/log
      - ${PWD}/fs/volumes/sqlserver/secrets:/var/opt/mssql/secrets
    environment:
      MSSQL_SA_PASSWORD: "MySuperPassword-128935"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    networks:
      - sqlserver-network
    